"""
Report Generator — Produces a structured Markdown research report.

USING OUTPUT STRUCTURE TO ENFORCE QUALITY
==========================================
Instead of letting the LLM free-form its output, we define the report
sections up front:

  1. Overview
  2. Papers Analysed
  3. Key Findings
  4. Contradictions
  5. Research Gaps
  6. Suggested Next Steps
  7. Limitations

By writing the Markdown skeleton ourselves and filling in the LLM-generated
content at specific slots, we guarantee the report always has the sections
the reader expects. This is a lightweight alternative to LangChain output
parsers — useful when your output is a document rather than structured data.

For more complex cases, LangChain provides output parsers
(StructuredOutputParser, PydanticOutputParser) that can enforce JSON schemas
on LLM responses. Here, Markdown is the natural format so we build it
directly.
"""

import os
from datetime import datetime, timezone


def generate_report(analysis_results: dict, output_path: str) -> str:
    """Generate a Markdown research report and save it to disk.

    Args:
        analysis_results: Dict containing:
            - raw_analysis (str): The gap analysis text from the LLM.
            - papers_analysed (int): Count of papers.
            - paper_titles (list[str]): Titles of analysed papers.
            Optionally:
            - agent_findings (str): Additional findings from the agent.
        output_path: File path to write the .md report.

    Returns:
        The full report as a string.
    """
    # --- Build the report section by section ---
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    paper_titles = analysis_results.get("paper_titles", [])
    papers_list = "\n".join(
        f"  {i}. {title}" for i, title in enumerate(paper_titles, 1)
    ) or "  No papers analysed."

    raw_analysis = analysis_results.get("raw_analysis", "No analysis available.")
    agent_findings = analysis_results.get("agent_findings", "")

    # The report template — each section is clearly delimited so readers
    # always know where to find what they need.
    report = f"""# 📚 AI Research Agent — Analysis Report

> Generated on: {timestamp}
> Papers analysed: {analysis_results.get('papers_analysed', 0)}

---

## 1. Overview

This report was automatically generated by the AI Research Agent. It
synthesises information from the papers listed below, identifies key
findings, contradictions, and gaps in the existing research.

**⚠️ Important:** LLMs can hallucinate citations and findings. Always verify
claims against the original papers before relying on this report.

---

## 2. Papers Analysed

{papers_list}

---

## 3. Gap Analysis

{raw_analysis}

---
"""

    # Optionally append agent-gathered findings
    if agent_findings:
        report += f"""
## 4. Additional Agent Findings

{agent_findings}

---
"""

    report += f"""
## Limitations

- This analysis was performed by an LLM and may contain inaccuracies.
- Only the papers listed above were considered; relevant work may have
  been missed.
- The quality of extraction depends on PDF formatting quality.
- Always cross-reference with the original papers.

---

*Report generated by AI Research Agent • {timestamp}*
"""

    # --- Write to disk ---
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"📝 Report saved to {output_path}")
    return report
